### ISSUE TITLE
Support caching of maps across multiple mapStackTrace calls

### ISSUE THREAD

**Issue by dwelle** [novocaine/sourcemapped-stacktrace#13]
if I call `mapStackTrace` many times, it should be able to cache maps for the same files across those calls, and not refetch them every time.

Use case: using `mapStackTrace` inside jasmine reporter where it's called for every failed spec (which can be tens of calls).

I can issue a PR and make the `mapStackTrace` share a global `fetcher.mapForUri` (if user passes an option to allow this behavior). There's also a need to check `fetcher.sem === 0` after we loop through `lines` and call `fetchScript`, to call `done` callback right away if need be. Not sure if it shouldn't be done in a cleaner way.

**Comment by novocaine** [comment]
If your server emits appropriate cache-control headers for your static .js file files, won't the browser pull them from it's cache? Does smst somehow impede that?

**Comment by dwelle** [comment]
Yea, depends on whether I have disabled cache in devTools, which I have pretty much all the time to mitigate caching problems during development. Even if not, cache retrieval takes ~2-6ms which can add up fast.

**Comment by novocaine** [comment]
Okay, I can see how that's a common scenario for smst users.

Happy to look at your PR.

**Comment by dwelle** [comment]
Ok, I'll issue it once we deal with https://github.com/novocaine/sourcemapped-stacktrace/pull/15, for better merge

**Comment by x1B** [comment]
Would love to get this feature in as well 👍

**Comment by novocaine** [comment]
yeah sorry for dragging, i'll try to get this in this week.

**Comment by x1B** [comment]
@novocaine no biggy, whenever you get to it!
