### ISSUE TITLE
Support filtering stack sources

### ISSUE THREAD

**Issue by dwelle** [novocaine/sourcemapped-stacktrace#14]
We should be able to supply e.g. a regexp to filter the stack sources and map only those that match. E.g., if I use this for mapping stack from jasmine reporter, I'm interested in just my `.spec.js` files, and not in the `jasmine.js` library.

It's super easy to add this, but I'm not sure what's the best way. Third `opts` argument with `{RegExp} opts.filter`?

**Comment by novocaine** [comment]
Is the goal just to reduce the number of network requests so you can get your mapped traces faster?

**Comment by dwelle** [comment]
That & save time on sourceMap processing, right?

**Comment by novocaine** [comment]
Sounds great. 

Can we add an opts.filter which is just a predicate function (line) -> bool ? More flexible than regex.

Also please update the documentation in the README

Thanks :)

**Comment by dwelle** [comment]
Btw, should it just not process, or completely exclude from output? (Or allow some opts to include/exclude?)

**Comment by novocaine** [comment]
It should still appear in the trace but it should be original unmapped line
