### ISSUE TITLE
Usage in node.js

### ISSUE THREAD

**Issue by gkostov** [novocaine/sourcemapped-stacktrace#24]
I have this case here that the app logs the exceptions to the server and those are then processed/redirected further. Therefore I would like to have the stack trace to be processed in node.js (either by the time it is logged or later) and not to have to run a browser or anything else.
I would prefer to avoid creating yet another sourcemapper module and could take this one as a base and decompose it in a way that loading the source map files will be configurable (either load via AJAX as it currently does or let the module consumer provide the content from the file system maybe).

So I have these questions:
1) Are you willing to accept a pull request to update the code with this new functionality? It would mean splitting the module into multiple files so the build step can produce a stripped down version for use in the browser.
2) You note that "Currently only Chrome and Firefox format is supported" but seems the code tries to handle IE as well (https://github.com/novocaine/sourcemapped-stacktrace/blob/master/sourcemapped-stacktrace.js#L234-L236). What is the reason?

Thanks a lot

**Comment by novocaine** [comment]
Hi,

1. 

Really the only purpose of this module is to launch a series of AJAX requests and pipe the results through a SourceMapConsumer (which is provided by another library). It's 256 lines. If you want to do stuff with files instead, it is likely easier for you to just write your own thing (also using SourceMapConsumer) and it would be far fewer lines.

Given I barely find time to maintain this lib as-is I would probably not accept a pull request of any significant complexity but you are more than welcome to fork. I appreciate you asking first.

2. 

That's xmlhttprequest boilerplate that I copied off the internet. I suppose I could erase some of those lines to save some bytes. The point is that that IE stack trace format isn't supported.

**Comment by gkostov** [comment]
Thanks for the reply,

I'll likely go fork it so I won't need to re-implement the stack trace processing code. It supports the two major browsers so should be good enough for my needs. I would like to keep the in-browser option - it already exists anyway and might come useful somewhere ;-)

Cheers
