### ISSUE TITLE
skip_lines = 1 | undeclared variable ? 

### ISSUE THREAD

**Issue by MKervo** [novocaine/sourcemapped-stacktrace#28]
Hi,
I experience an issue with skip_lines = 1: ReferenceError.
This has been solved declaring: "var skip_line"s directly in the dist.
Am I missing something here ?
Thanks

**Comment by novocaine** [comment]
It looks like there has been a missing var declaration for quite a long time in the script, which we can fix up.

However, it is still legal javascript. I suspect you have incorrectly enabled strict mode somewhere, but the library (until we fix this) doesn't work in strict mode.

**Comment by novocaine** [comment]
fixed in #30
