### ISSUE TITLE
Is there a plan to release the skip_lines fix to npm?

### ISSUE THREAD

**Issue by rooskienz** [novocaine/sourcemapped-stacktrace#32]
Hi,

I'm getting the `skip_lines` undefined error, I can see that it has been fixed in github 2 months ago, but latest npm release was 4 months ago. is there a plan to release v 1.1.8 to npm?

Cheers

**Comment by novocaine** [comment]
released.

**Comment by rooskienz** [comment]
Awesome! Thanks!
