### ISSUE TITLE
provide dist folder

### ISSUE THREAD

**Issue by DanielSchuech** [novocaine/sourcemapped-stacktrace#5]
Could you please provide the bundle created by webpack in the dist folder in git.

Currently it would be necessary to go into your module, install webpack, npm run prepublish. It would be easier if you have only to install your module via npm and use it.

Regards, Daniel

**Comment by novocaine** [comment]
Thanks for letting me know!

Fixed in 1101feac3f72e4c051a6c08f045f2da5c34fa1be

**Comment by DanielSchuech** [comment]
Could you please commit your dist folder?

**Comment by novocaine** [comment]
I'd rather not commit a build.. is there a reason you're not using the package from npm (which now contains the dist folder) ?

**Comment by DanielSchuech** [comment]
Ah sry i didn't looked to the npm package(didn't know that could differ on files). Just had in mind that the dists are in other projects included in the repo. 

Thanks for the fast fix and your nice work ;)
