### ISSUE TITLE
NPM release for 1.1.0

### ISSUE THREAD

**Issue by jwhitfieldseed** [novocaine/sourcemapped-stacktrace#7]
Thanks for this project, I'm finding it very useful :+1: 

Could you cut an npm release for 1.1.0, so CommonJS users can benefit from the package.json `main` field?

Thanks!

**Comment by novocaine** [comment]
Sure, I do mean to but I was on holiday last weekend, should be able to cut it later today

**Comment by novocaine** [comment]
Done.
