### ISSUE TITLE
UMD support + bundle

### ISSUE THREAD

**Issue by finom** [novocaine/sourcemapped-stacktrace#8]
Subj

**Comment by novocaine** [comment]
Thank you for the brevity of your request.

Does the UMD output of webpack not work for you?

https://github.com/novocaine/sourcemapped-stacktrace/blob/master/webpack.config.js#L6

**Comment by finom** [comment]
I didn't try it actually. My request means that it could be useful to have ready-to-use UMD bundle in repo with no need to pull and bundle it manually.

**Comment by novocaine** [comment]
The bundle is included in the npm package.

https://www.npmjs.com/package/sourcemapped-stacktrace

I don't want check build artifacts into source control.

**Comment by finom** [comment]
OK
